<?php

/**
 * OrderDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderDetailTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrderDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderDetail');
    }
}