<?php

/**
 * DmAutoSeoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmAutoSeoTable extends PluginDmAutoSeoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmAutoSeoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmAutoSeo');
    }
}