<?php

/**
 * DmErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmErrorTable extends PluginDmErrorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmError');
    }
}