<?php

/**
 * DmMediaFolderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmMediaFolderTable extends PluginDmMediaFolderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmMediaFolderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmMediaFolder');
    }
}