<?php

/**
 * DmPageViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmPageViewTable extends PluginDmPageViewTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmPageViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmPageView');
    }
}