<?php

/**
 * DmPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmPageTable extends PluginDmPageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmPageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmPage');
    }
}