<?php

/**
 * DmWidgetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmWidgetTable extends PluginDmWidgetTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmWidgetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmWidget');
    }
}