<?php

/**
 * DmZoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmZoneTable extends PluginDmZoneTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmZoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmZone');
    }
}