<?php

/**
 * DmGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmGroupPermissionTable extends PluginDmGroupPermissionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmGroupPermission');
    }
}