<?php

/**
 * DmRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmRememberKeyTable extends PluginDmRememberKeyTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmRememberKey');
    }
}