<?php

/**
 * DmUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmUserGroupTable extends PluginDmUserGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmUserGroup');
    }
}