<?php

/**
 * DmUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DmUserTable extends PluginDmUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DmUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DmUser');
    }
}